repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5  # or specific git tag
    hooks:
      - id: shellcheck
        args:
          - "-e"
          - "SC1090"
          - "-e"
          - "SC1091"
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.6.0"
    hooks:
      - id: hadolint-docker
        args:
          - --ignore
          - DL4006
          - --ignore
          - DL3015
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-github-workflows
